config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'feed#show'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resource :profile, only: %i[show update], controller: 'users'

  resources :listings, except: :index

  namespace :users do
    patch 'change_password', to: 'passwords#update'
    resources :password_resets, only: %i[new create edit update]
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :organization

  enum condition: {
    mint: "mint", near_mint: "near_mint",
    used: "used", defective: "defective"
  }

  validates :title, length: { in: 10..100 }
  validates :price, numericality: { only_integer: true }
  validates :condition, presence: true

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :load_listing, except: [:new, :create]
  allow_unauthenticated only: :show

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(
      listing_params.with_defaults(
        creator: Current.user,
        organization: Current.organization
      )
    )
    if @listing.save
      redirect_to listing_path(@listing),
                  flash: { success: t(".success") },
                  status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing),
                  status: :see_other,
                  flash: { success: t(".success") }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy
    redirect_to root_path,
                status: :see_other,
                flash: { success: t(".success") }
  end

  private

  def listing_params
    params.require(:listing).permit(
      :title, :price, :condition
    )
  end

  def load_listing
    @listing = Listing.find(params[:id])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%# locals: (form:) -%>
<div class="block">
  <%= form.label :title, class: "label" %>
  <%= form.text_field :title, class: "input is-large" %>
</div>

<layout-columns class="columns is-centered">
  <layout-column class="box column is-half mt-6 p-5 m-4">
    <div class="is-flex is-flex-direction-column">
      <form-field class="field">
        <%= form.label :price, class: "label" %>
        <form-field class="field has-addons">
          <p class="control">
            <a class="button is-static">
              £
            </a>
          </p>
          <p class="control is-expanded">
            <%= form.text_field :price, inputmode: :numeric, class: "input" %> </p>
        </form-field>
      </form-field>

      <form-field class="field">
        <%= form.label :condition, class: "label" %>
        <div class="select is-fullwidth">
          <%= form.select :condition, Listing.human_enum_options(:condition) %>
        </div>
      </form-field>
    </div>
  </layout-column>
  <layout-column class="box column is-half mt-6 p-5 m-4">
  </layout-column>
</layout-columns>

app/views/listings/edit.html.erb
<%= content_for(:title) do %>
  <%= @listing.title %>
<% end %>
<layout-columns class="columns is-centered">
  <%= form_with(
        model: @listing,
        class: "column is-10",
        id: "edit_listing_form"
      ) do |form| %>
    <%= render "form", form: form %>
  <% end %>
</layout-columns>

<layout-columns class="columns is-centered">
  <layout-column class="column is-10">
    <layout-group class="buttons is-right">
      <%= button_to t(".delete"), listing_path(@listing),
                    method: :delete,
                    form: { data: {
                      turbo_confirm: t(".confirm_delete")
                    } },
                    class: "button is-danger is-medium m-3" %>
      <%= submit_tag t(".publish"),
                     form: "edit_listing_form",
                     class: "button is-primary is-medium m-3" %>
    </layout-group>
  </layout-column>
</layout-columns>

app/views/listings/new.html.erb
<%= content_for(:title) do %>
  <%= t(".title") %>
<% end %>

<layout-columns class="columns is-centered">
  <%= form_with(
        model: @listing,
        class: "column is-10",
        id: "new_listing_form"
      ) do |form| %>
    <%= render "form", form: form %>
  <% end %>
</layout-columns>

<layout-columns class="columns is-centered">
  <layout-column class="column is-10">
    <layout-group class="buttons is-right">
      <%= submit_tag t(".publish"),
                     form: "new_listing_form",
                     class: "button is-primary is-medium m-3" %>
    </layout-group>
  </layout-column>
</layout-columns>

app/views/listings/show.html.erb
<%= content_for(:title) do %>
  <%= @listing.title %>
<% end %>

<layout-columns class="columns is-centered">
  <layout-column class="column is-10">
    <div class="mb-3">
      <h1 class="title is-inline">
        <%= @listing.title %>
      </h1>
      <%= link_to t(".edit"), edit_listing_path(@listing) %>
    </div>
    <layout-columns class="columns is-centered">
      <layout-column class="box column is-half mt-6 p-5 m-4">
        <dl>
          <dt class="has-text-grey">
            <%= t(".posted_by") %>
          </dt>
          <dd class="has-text-weight-semibold is-size-5">
            <%= @listing.creator.name %> </dd>
        </dl>
        <layout-group class="buttons mt-6">
          <%= button_to "#", class: "button is-secondary is-medium" do %>
            <%= svg "heart", class: "icon is-small mr-3" %>
            <%= t(".save") %>
          <% end %>
          <%= link_to "#", class: "button is-primary is-medium" do %>
            <%= svg("message",
                    class: "icon is-small mr-3",
                    fill: "#fff") %>
            <%= t(".contact") %>
          <% end %>
        </layout-group>
      </layout-column>
      <layout-column class="box column is-half mt-6 p-5 m-4">
        <dl>
          <dt class="has-text-grey">
            <%= Listing.human_attribute_name(:price) %>
          </dt>
          <dd class="has-text-weight-semibold is-size-5">
            <%= "£#{@listing.price}" %>
          </dd>

          <br>

          <dt class="has-text-grey">
            <%= Listing.human_attribute_name(:condition) %>
          </dt>
          <dd class="has-text-weight-semibold is-size-5">
            <%= @listing.human_enum_value(:condition) %>
          </dd>
        </dl>
      </layout-column>
    </layout-columns>
  </layout-column>
</layout-columns>