config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'feed#show'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resource :profile, only: %i[show update], controller: 'users'

  resources :listings, except: :index

  namespace :users do
    patch 'change_password', to: 'passwords#update'
    resources :password_resets, only: %i[new create edit update]
  end
end

app/models/app_session.rb
class AppSession < ApplicationRecord
  belongs_to :user

  has_secure_password :token, validations: false

  before_create do
    self.token = self.class.generate_unique_secure_token
  end

  def to_h
    {
      user_id: user.id,
      app_session: id,
      token:
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include HumanEnum
  
  primary_abstract_class
end

app/models/concerns/human_enum.rb
module HumanEnum
  extend ActiveSupport::Concern
  class_methods do
    def human_enum_name(enum_name, enum_value)
      model_key = model_name.i18n_key
      enum_key = enum_name.to_s.pluralize
      I18n.t(
        "activerecord.attributes." \
          "#{model_key}.#{enum_key}.#{enum_value}",
        default: enum_value.to_s.humanize
      )
    end

    def human_enum_options(enum_name)
      send(enum_name.to_s.pluralize).map do |key, value|
        [human_enum_name(enum_name, key), key]
      end.to_h
    end
  end

  def human_enum_value(enum_name)
    enum_value = send(enum_name)
    self.class.human_enum_name(enum_name, enum_value)
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user, :app_session, :organization
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :organization

  enum condition: {
    mint: "mint", near_mint: "near_mint",
    used: "used", defective: "defective"
  }

  validates :title, length: { in: 10..100 }
  validates :price, numericality: { only_integer: true }
  validates :condition, presence: true

end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  include Authentication, PasswordReset
  # before_validation :strip_extraneous_spaces

  validates :name, presence: true
  validates :email,
            format: { with: URI::MailTo::EMAIL_REGEXP },
            uniqueness: { case_sensitive: false }

  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships

  normalizes :name, with: ->(name) { name.strip }
  normalizes :email, with: ->(email) { email.strip.downcase }
end

app/models/user/authentication.rb
module User::Authentication
  extend ActiveSupport::Concern

  included do
    has_secure_password
    validates :password, on: %i[create password_change], presence: true, length: { minimum: 8 }

    has_many :app_sessions
  end

  class_methods do
    def create_app_session(email:, password:)
      user = User.authenticate_by(email:, password:)
      user.app_sessions.create if user.present?
    end
  end

  def authenticate_app_session(app_session_id, token)
    app_sessions.find(app_session_id).authenticate_token(token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/models/user/password_reset.rb
# frozen_string_literal: true

module User::PasswordReset
  extend ActiveSupport::Concern

  included do
    generates_token_for :password_reset, expires_in: 2.hours do
      password_salt.last(10)
    end
  end

  def reset_password
    app_sessions.destroy_all
    send_password_reset_email
  end

  private

  def send_password_reset_email
    token = generate_token_for(:password_reset)
    UserMailer.with(user: self).password_reset(token).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticate
  include SetCurrentRequestDetails

  helper_method :turbo_frame_request?
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  allow_unauthenticated

  def show
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :load_listing, except: [:new, :create]
  allow_unauthenticated only: :show

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(
      listing_params.with_defaults(
        creator: Current.user,
        organization: Current.organization
      )
    )
    if @listing.save
      redirect_to listing_path(@listing),
                  flash: { success: t(".success") },
                  status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing),
                  status: :see_other,
                  flash: { success: t(".success") }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy
    redirect_to root_path,
                status: :see_other,
                flash: { success: t(".success") }
  end

  private

  def listing_params
    params.require(:listing).permit(
      :title, :price, :condition
    )
  end

  def load_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_authentication only: %i[new create]

  def new
  end

  def create
    @app_session = User.create_app_session(
      email: login_params[:email],
      password: login_params[:password]
    )

    if @app_session
      log_in(@app_session)
      flash[:success] = t('.success')
      redirect_to root_path, status: :see_other
    else
      flash.now[:danger] = t('.incorrect_details')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    log_out

    flash[:success] = t('.success')
    redirect_to root_path, status: :see_other
  end

  private

  def login_params
    @login_params ||= params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authentication only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @organization = Organization.create(members: [@user])
      @app_session = @user.app_sessions.create
      log_in(@app_session)

      redirect_to root_path,
                  status: :see_other,
                  flash: { success: t('.welcome', name: @user.name) }
    else
      render :new, status: :unprocessable_entity end
  end

  def show
    @user = Current.user
  end

  def update
    @user = Current.user

    if @user.update(update_params)
      flash[:success] = t('.success')
      redirect_to profile_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def update_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    return t("piazza") unless content_for?(:title)

    "#{content_for(:title)} | #{t("piazza")}"
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/svg_helper.rb
module SvgHelper
  def svg(svg_name, **attributes)
    svg_markup =
      render file: "#{Rails.root}/app/views/application/svg/#{svg_name}.svg"
    xml = Nokogiri::XML(svg_markup)
    attributes&.each do |key, value|
      xml.root.set_attribute(key, value)
    end
    xml.root.to_xml.html_safe
  end
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flashes.html.erb
 <%# locals: () -%>
<div class="container is-fluid" data-turbo-temporary> <% flash.each do |level, message| %>
    <%= tag.div class: "notification is-#{level} is-light has-text-centered mt-4" do %>
      <%= message %>
    <% end %>
  <% end %>
</div>

app/views/application/_form_errors.html.erb
<%# locals: (html_tag:, instance:) -%>
<% unless html_tag =~ /^<label/ %>
  <% field_html = Nokogiri::HTML::DocumentFragment.parse(html_tag) %>
  <% field_html.children.add_class("is-danger") %>
  <%== field_html %>
  <p class='help is-danger'>
    <%= instance.error_message.to_sentence %>
  </p>
<% else %>
  <%= html_tag %>
<% end %>

app/views/application/_navbar.html.erb
<%# locals: () -%>
<nav class="navbar is-link" data-controller="navbar">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <strong class="is-size-3">Piazza</strong>
    <% end %>
    <a role="button" class="navbar-burger" data-navbar-target="burger" data-action="navbar#toggle">
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>
  <navbar-menu class="navbar-menu" data-navbar-target="menu">
    <div class="navbar-start">
      <%= link_to t(".create_ad"), new_listing_path, class: "navbar-item" %>
      <%= link_to t(".messages"), "#", class: "navbar-item" if logged_in? %>
    </div>
    <div class="navbar-end">
      <%= tag.div class: "navbar-item has-dropdown is-hoverable mr-4" do %>
        <%= link_to Current.user.name, profile_path, id: "current_user_name", class: "navbar-link" %>
        <div class="navbar-dropdown is-right">
          <%= link_to t(".profile"), profile_path, class: "navbar-item" %>
          <%= link_to t(".my_ads"), "#", class: "navbar-item" %>
          <%= link_to t(".saved_ads"), "#", class: "navbar-item" %>
          <hr class="navbar-divider">
          <%= link_to t(".logout"), logout_path, class: "navbar-item", data: { turbo_method: :delete } %>
        </div>
      <% end if logged_in? %>
      <%= tag.div class: "navbar-item" do %>
        <div class="buttons">
          <%= link_to t(".sign_up"), sign_up_path, class: "button is-primary" %>
          <%= link_to t(".login"), login_path, class: "button is-light" %>
        </div>
      <% end unless logged_in? %>
    </div>
  </navbar-menu>
</nav>

app/views/feed/show.html.erb
<h1>Feed#show</h1>
<p>Find me in app/views/feed/show.html.erb</p>